// <auto-generated />
using System;
using JuliusFinances.Api.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JuliusFinances.Api.Migrations
{
    [DbContext(typeof(JuliusDbContext))]
    [Migration("20260706232134_AddTransactionEntity")]
    partial class AddTransactionEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JuliusFinances.Core.Modules.Auth.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("JuliusFinances.Core.Modules.FinancesSetup.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_balance");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("idx_accounts_owner_name_active")
                        .HasFilter("is_deleted = false");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("JuliusFinances.Core.Modules.FinancesSetup.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("flow_type");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("de250001-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Expense",
                            IsDeleted = false,
                            Name = "Alimentação"
                        },
                        new
                        {
                            Id = new Guid("de250002-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Expense",
                            IsDeleted = false,
                            Name = "Habitação"
                        },
                        new
                        {
                            Id = new Guid("de250003-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Expense",
                            IsDeleted = false,
                            Name = "Transporte"
                        },
                        new
                        {
                            Id = new Guid("de250004-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Expense",
                            IsDeleted = false,
                            Name = "Saúde"
                        },
                        new
                        {
                            Id = new Guid("de250005-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Expense",
                            IsDeleted = false,
                            Name = "Educação"
                        },
                        new
                        {
                            Id = new Guid("de250006-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Expense",
                            IsDeleted = false,
                            Name = "Lazer & Entretenimento"
                        },
                        new
                        {
                            Id = new Guid("de250007-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Expense",
                            IsDeleted = false,
                            Name = "Serviços & Assinaturas"
                        },
                        new
                        {
                            Id = new Guid("de250008-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Expense",
                            IsDeleted = false,
                            Name = "Outras Despesas"
                        },
                        new
                        {
                            Id = new Guid("de250009-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Income",
                            IsDeleted = false,
                            Name = "Salário"
                        },
                        new
                        {
                            Id = new Guid("de250010-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Income",
                            IsDeleted = false,
                            Name = "Investimentos"
                        },
                        new
                        {
                            Id = new Guid("de250011-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Income",
                            IsDeleted = false,
                            Name = "Freelance / Serviços"
                        },
                        new
                        {
                            Id = new Guid("de250012-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Income",
                            IsDeleted = false,
                            Name = "Presentes / Prêmios"
                        },
                        new
                        {
                            Id = new Guid("de250013-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Income",
                            IsDeleted = false,
                            Name = "Outras Receitas"
                        },
                        new
                        {
                            Id = new Guid("de250014-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Both",
                            IsDeleted = false,
                            Name = "Transferência"
                        },
                        new
                        {
                            Id = new Guid("de250015-c812-4c22-9014-99859f123456"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowType = "Both",
                            IsDeleted = false,
                            Name = "Ajuste de Saldo"
                        });
                });

            modelBuilder.Entity("JuliusFinances.Core.Modules.FinancesSetup.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("OwnerId", "AccountId")
                        .HasDatabaseName("idx_transactions_owner_account");

                    b.HasIndex("OwnerId", "TransactionDate")
                        .HasDatabaseName("idx_transactions_owner_date");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("JuliusFinances.Core.Modules.FinancesSetup.Domain.Entities.Transaction", b =>
                {
                    b.OwnsOne("JuliusFinances.Core.Modules.FinancesSetup.Domain.ValueObjects.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId")
                                .HasConstraintName("fk_transactions_transactions_id");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
